---

- hosts: myhosts
  tasks:
    - name: Import the Datadog Agent role from the Datadog collection
      import_role:
        name: datadog.dd.agent
      become: true
  vars:
    datadog_api_key: "{{ lookup('ansible.builtin.env', 'DD_API_KEY') }}"
    datadog_site: "us3.datadoghq.com"
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd']
          - name: syslog
            search_string: ['rsyslog']
            cpu_check_interval: 0.2
            exact_match: true
            ignore_denied_access: true
